# Generated by Django 2.2 on 2020-12-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='UserProfile',
            new_name='userprofile',
        ),
    ]
